[package]
name = "nossal"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
askama = { version = "0.12.1", features = ["with-actix-web"] }
askama_actix = "0.14.0"
env_logger = "0.11.5"
log = "0.4.22"
pulldown-cmark = "0.12.2"
yaml-front-matter = "0.1.0"

[dev-dependencies]
cargo-watch = "8.5.3"
