[package]
name = "nossal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
askama = { version = "0.12.1", features = ["with-actix-web", "markdown"] }
